# Generated by Django 6.1.1 on 2026-09-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('META_ADS', 'Meta Ads'), ('GOOGLE_ADS', 'Google Ads'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk In'), ('CALL', 'Call'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('requirement_type', models.CharField(choices=[('VILLA', 'Villa'), ('APARTMENT', 'Apartment'), ('PLOT', 'Plot'), ('FARM_LAND', 'Farm Land'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('preferred_project', models.CharField(blank=True, max_length=250)),
                ('bhk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('SITE_VISIT', 'Site Visit'), ('NEGOTIATION', 'Negotiation'), ('BOOKED', 'Booked'), ('LOST', 'Lost'), ('NOT_INTERESTED', 'Not Interested')], default='NEW', max_length=30)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
