# Generated by Django 6.1.1 on 2026-09-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('projects', '0002_project_amenities_project_bhk_and_more'),
    ]
operations = [
    migrations.RemoveField(
        model_name='lead',
        name='preferred_project',
    ),
    migrations.RemoveField(
        model_name='lead',
        name='requirement_type',
    ),
    migrations.RemoveField(
        model_name='lead',
        name='whatsapp_number',
    ),
    migrations.AddField(
        model_name='lead',
        name='interested_project',
        field=models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='leads',
            to='projects.project'
        ),
    ),
    migrations.AddField(
        model_name='lead',
        name='preferred_property_type',
        field=models.CharField(
            blank=True,
            max_length=50
        ),
    ),
    migrations.AddField(
        model_name='lead',
        name='requirement',
        field=models.TextField(
            blank=True
        ),
    ),
    migrations.AlterField(
        model_name='lead',
        name='source',
        field=models.CharField(
            choices=[
                ('META_ADS', 'Meta Ads'),
                ('GOOGLE_ADS', 'Google Ads'),
                ('WEBSITE', 'Website'),
                ('INSTAGRAM', 'Instagram'),
                ('FACEBOOK', 'Facebook'),
                ('WHATSAPP', 'WhatsApp'),
                ('REFERRAL', 'Referral'),
                ('WALK_IN', 'Walk In'),
                ('CALL', 'Direct Call'),
                ('OTHER', 'Other'),
            ],
            default='OTHER',
            max_length=30
        ),
    ),
    migrations.AlterField(
        model_name='lead',
        name='status',
        field=models.CharField(
            choices=[
                ('NEW', 'New'),
                ('CONTACTED', 'Contacted'),
                ('INTERESTED', 'Interested'),
                ('SITE_VISIT', 'Site Visit'),
                ('NEGOTIATION', 'Negotiation'),
                ('BOOKED', 'Booked'),
                ('LOST', 'Lost'),
                ('ON_HOLD', 'On Hold'),
            ],
            default='NEW',
            max_length=30
        ),
    ),
]