# Generated by Django 6.1.1 on 2026-09-19 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_preferred_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('SITE_VISIT', 'Site Visit'), ('MEETING', 'Meeting'), ('FOLLOW_UP', 'Follow Up'), ('NOTE', 'Note')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
        ),
    ]
