# Generated by Django 6.1.1 on 2026-09-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('project_type', models.CharField(choices=[('VILLAS', 'Villas'), ('APARTMENTS', 'Apartments'), ('PLOTS', 'Plots'), ('FARM_LANDS', 'Farm Lands'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('total_land_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_units', models.PositiveIntegerField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100)),
                ('rera_status', models.CharField(blank=True, max_length=50)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='developers.developer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.location')),
            ],
        ),
    ]
