# Generated by Django 6.1.1 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_amenities_project_bhk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="developers.developer",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="locations.location",
            ),
        ),
    ]
