# Generated by Django 6.1.1 on 2026-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_price_from_project_price_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price_to',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('PRE_LAUNCH', 'Pre Launch'), ('LAUNCHED', 'Launched'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_MOVE', 'Ready to Move'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('INACTIVE', 'Inactive')], default='COMING_SOON', max_length=30),
        ),
    ]
