# Generated by Django 6.1.1 on 2026-09-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='project_status',
        ),
    ]
