# Generated by Django 6.1.1 on 2026-09-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('VILLA', 'Villa'), ('APARTMENT', 'Apartment'), ('PLOT', 'Plot'), ('COMMERCIAL', 'Commercial'), ('FARM_LAND', 'Farm Land'), ('OTHER', 'Other')], max_length=30)),
                ('bhk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plot_size_sq_yards', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_size_sq_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saleable_area_sq_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('built_up_area_sq_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_built_up_area_sq_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('facing', models.CharField(blank=True, max_length=50)),
                ('floors', models.CharField(blank=True, max_length=100)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_plan', models.TextField(blank=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100)),
                ('amenities', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('ON_HOLD', 'On Hold'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='projects.project')),
            ],
        ),
    ]
