# Generated by Django 6.1.1 on 2026-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amenities_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='available_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='basic_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='basic_sale_price_per_sq_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='brochure_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='commission_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cp_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='facing_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_sheet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='offer_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_per_sq_ft_incl_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_sheet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_facing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_size_sq_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
