# Generated by Django 6.1.1 on 2026-09-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_basic_sale_price_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unit_number',
        ),
    ]
