# Generated by Django 6.1.1 on 2026-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventory_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='brochure_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='commission_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='facing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='floors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='payment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price_sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rera_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_facing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
