# Generated by Django 6.1.1 on 2026-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_amenities_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='basic_sale_price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='extra_built_up_rate_per_sq_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
